spring:  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234    


token:
  expiration_time: 86400000  # 1일 ( 1000 * 60 * 60 * 24 )
  secret: user_token
